<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Id</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Server.DemoHost.TestClient/Server.DemoHost.TestClient.csproj" />
    <ProjectReference Include="../Server.Host.TestClient/Server.Host.TestClient.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.AspNetCore.IntegrationTesting" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <None Update="keys/*.key" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
