version: '3.7'
x-base: &base
  restart: always
  logging:
    driver: json-file
    options:
      max-size: 1m
      max-file: '1'
services:
  api:
    <<: *base
    build:
      context: .
      dockerfile: src/api/Annium.Id.Api/app.dockerfile
    image: id_api
    container_name: id_api
    ports:
      - '9501:5000'
    volumes:
      - './run/api/configuration:/app/configuration'
      - './run/api/keys:/app/keys'
  db:
    <<: *base
    image: registry.annium.com/postgres
    container_name: id_db
    ports:
      - '9591:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    env_file: ./run/db/db.env
  site:
    <<: *base
    build:
      context: ./src/web/Annium.Id.Site
      dockerfile: site.dockerfile
    image: id_site
    container_name: id_site
    ports:
      - '9500:80'
volumes:
  db:
