// <auto-generated />
using System;
using Annium.Id.Db.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Annium.Id.Db.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190415102041_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Annium.Id.Db.Entities.App", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("ApiToken");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid>("OwnerId");

                    b.HasKey("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("OwnerId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AppId");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("AppId", "Key");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Company", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid>("OwnerId");

                    b.Property<Guid?>("ParentId");

                    b.HasKey("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyClaim", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AppId");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("AppId", "Key");

                    b.ToTable("CompanyClaims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyRole", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AppId");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("AppId", "Key");

                    b.ToTable("CompanyRoles");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyRoleClaim", b =>
                {
                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("ClaimId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("RoleId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("CompanyRoleClaims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyUser", b =>
                {
                    b.Property<Guid>("CompanyId");

                    b.Property<Guid>("UserId");

                    b.HasKey("CompanyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyUserClaim", b =>
                {
                    b.Property<Guid>("CompanyId");

                    b.Property<Guid>("UserId");

                    b.Property<Guid>("ClaimId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("CompanyId", "UserId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyUserClaims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyUserRole", b =>
                {
                    b.Property<Guid>("CompanyId");

                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("CompanyId", "UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyUserRoles");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Role", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AppId");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("AppId", "Key");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.RoleClaim", b =>
                {
                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("ClaimId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("RoleId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.User", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.HasAlternateKey("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserClaim", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("ClaimId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("UserId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserLogin", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Client")
                        .IsRequired();

                    b.Property<string>("IPAddress")
                        .IsRequired();

                    b.Property<DateTime>("LoggedAt");

                    b.Property<Guid>("RefreshToken");

                    b.Property<DateTime>("RefreshTokenExpires");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasAlternateKey("RefreshToken");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.App", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Claim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Company", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.Company")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyClaim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyRole", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyRoleClaim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.CompanyClaim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.CompanyRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyUser", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyUserClaim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.CompanyClaim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.CompanyUserRole", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.CompanyRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Role", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.RoleClaim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserClaim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserLogin", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserRole", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
