// <auto-generated />
using System;
using Annium.Id.Db.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Annium.Id.Db.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190411105614_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Annium.Id.Db.Entities.App", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("ApiToken");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid>("OwnerId");

                    b.HasKey("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("OwnerId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AppId");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("AppId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid>("OwnerId");

                    b.Property<Guid>("ParentId");

                    b.HasKey("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationClaim", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AppId");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("AppId");

                    b.ToTable("OrganizationClaims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationRole", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AppId");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("AppId");

                    b.ToTable("OrganizationRoles");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationRoleClaim", b =>
                {
                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("ClaimId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("RoleId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("OrganizationRoleClaims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationUser", b =>
                {
                    b.Property<Guid>("OrganizationId");

                    b.Property<Guid>("UserId");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationUsers");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationUserClaim", b =>
                {
                    b.Property<Guid>("OrganizationId");

                    b.Property<Guid>("UserId");

                    b.Property<Guid>("ClaimId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("OrganizationId", "UserId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationUserClaims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationUserRole", b =>
                {
                    b.Property<Guid>("OrganizationId");

                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("OrganizationId", "UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationUserRoles");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Role", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AppId");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("AppId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.RoleClaim", b =>
                {
                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("ClaimId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("RoleId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.User", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<Instant>("LockedUntil");

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.Property<int>("TryCount");

                    b.HasKey("Id");

                    b.HasAlternateKey("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserClaim", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("ClaimId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("UserId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserLogin", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Client")
                        .IsRequired();

                    b.Property<string>("IPAddress")
                        .IsRequired();

                    b.Property<Instant>("LoggedAt");

                    b.Property<Guid>("RefreshToken");

                    b.Property<Instant>("RefreshTokenExpires");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.App", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Claim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Organization", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.Organization")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationClaim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationRole", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationRoleClaim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.OrganizationClaim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.OrganizationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationUser", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationUserClaim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.OrganizationClaim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.OrganizationUserRole", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.OrganizationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.Role", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.RoleClaim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserClaim", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserLogin", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Annium.Id.Db.Entities.UserRole", b =>
                {
                    b.HasOne("Annium.Id.Db.Entities.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annium.Id.Db.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
