<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Annium.Id.Api</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Annium id entrypoint</Description>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <WarningsAsErrors>true</WarningsAsErrors>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <None Update="**/locale/*.yml" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../Annium.Id.AspNetCore/Annium.Id.AspNetCore.csproj" />
        <ProjectReference Include="../Annium.Id.Db/Annium.Id.Db.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Extensions.Localization" Version="0.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
        <PackageReference Include="NodaTime.Serialization.JsonNet" Version="2.2.0" />
        <PackageReference Include="NSwag.AspNetCore" Version="13.0.4" />
    </ItemGroup>
</Project>