version: '3.7'
services:
  db:
    image: registry.annium.com/postgres
    container_name: id_db
    restart: always
    ports:
      - '9591:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    env_file: ../run/db/db.env
networks:
  default:
    external:
      name: id_net
volumes:
  db:
