<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Server.ViewModels</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Server.ViewModels</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../../lib/src/Annium.Id.Core/Annium.Id.Core.csproj" />
        <ProjectReference Include="../Server.Domain/Server.Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Architecture.ViewModel" Version="0.1.0" />
    </ItemGroup>
</Project>