<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Id</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Architecture.CQRS" />
    <PackageReference Include="Annium.Data.Models" />
  </ItemGroup>
</Project>
