<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Id</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Annium.Id.Core/Annium.Id.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Data.Operations.Serialization.Json" />
    <PackageReference Include="Annium.Logging.Console" />
    <PackageReference Include="Annium.Logging.InMemory" />
    <PackageReference Include="Annium.Testing" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <None Update="keys/*.key" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
