<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <PackageId>Server.Host</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Annium id entrypoint</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../../lib/src/Annium.Id.AspNetCore/Annium.Id.AspNetCore.csproj" />
        <ProjectReference Include="../Server.Application/Server.Application.csproj" />
        <ProjectReference Include="../Server.ViewModels/Server.ViewModels.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Architecture.Http" Version="0.1.0" />
        <PackageReference Include="Annium.Configuration.CommandLine" Version="0.1.0" />
        <PackageReference Include="Annium.Infrastructure.Hosting" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Microsoft" Version="0.1.0" />
        <PackageReference Include="Annium.Net.Http" Version="0.1.0" />
        <PackageReference Include="Annium.NodaTime.Serialization.Json" Version="0.1.0" />
        <PackageReference Include="XRest.Plugins.AspNetCore" Version="0.1.0" />
    </ItemGroup>
    <ItemGroup>
        <None Update="**/locale/*.yml" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>