<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Annium.Id.Api.Application</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Annium.Id.Application</Description>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>latest</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../lib/Annium.Id.Core/Annium.Id.Core.csproj" />
        <ProjectReference Include="../../infrastructure/Annium.Id.Db/Annium.Id.Db.csproj" />
        <ProjectReference Include="../../infrastructure/Annium.Id.Infrastructure/Annium.Id.Infrastructure.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Architecture.CQRS" Version="0.1.0" />
        <PackageReference Include="Annium.Architecture.Mediator" Version="0.1.0" />
        <PackageReference Include="Annium.Diagnostics.Debug" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Validation" Version="0.1.0" />
        <PackageReference Include="Annium.Localization.Yaml" Version="0.1.0" />
    </ItemGroup>
    <ItemGroup>
        <None Update="**/locale/*.yml" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>