// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Db;

namespace Annium.Id.Infrastructure.DbMigrator.Migrations
{
    [DbContext(typeof(Context))]
    internal partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.App", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<Guid>("ApiToken")
                    .HasColumnName("api_token")
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnName("name")
                    .HasColumnType("text");

                b.Property<Guid>("OwnerId")
                    .HasColumnName("owner_id")
                    .HasColumnType("uuid");

                b.HasKey("Id")
                    .HasName("pk_apps");

                b.HasIndex("OwnerId")
                    .HasName("ix_apps_owner_id");

                b.ToTable("apps");

                b.HasData(
                    new
                    {
                        Id = new Guid("278e20ae-00c7-4ba5-8db3-55df7af12d44"),
                        ApiToken = new Guid("b62acd2a-2f1b-4da1-9273-abab4b9da7f7"),
                        Name = "Annium ID",
                        OwnerId = new Guid("baa0ad0f-91c5-4c19-963c-ea369048e67a")
                    });
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.Claim", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<Guid>("AppId")
                    .HasColumnName("app_id")
                    .HasColumnType("uuid");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasColumnName("key")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnName("name")
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("pk_claims");

                b.HasIndex("AppId", "Key")
                    .IsUnique()
                    .HasName("ix_claims_app_id_key");

                b.ToTable("claims");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.Company", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnName("name")
                    .HasColumnType("text");

                b.Property<Guid>("OwnerId")
                    .HasColumnName("owner_id")
                    .HasColumnType("uuid");

                b.Property<Guid?>("ParentId")
                    .HasColumnName("parent_id")
                    .HasColumnType("uuid");

                b.HasKey("Id")
                    .HasName("pk_companies");

                b.HasIndex("OwnerId")
                    .HasName("ix_companies_owner_id");

                b.HasIndex("ParentId")
                    .HasName("ix_companies_parent_id");

                b.ToTable("companies");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyClaim", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<Guid>("AppId")
                    .HasColumnName("app_id")
                    .HasColumnType("uuid");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasColumnName("key")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnName("name")
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("pk_company_claims");

                b.HasIndex("AppId", "Key")
                    .IsUnique()
                    .HasName("ix_company_claims_app_id_key");

                b.ToTable("company_claims");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyRole", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<Guid>("AppId")
                    .HasColumnName("app_id")
                    .HasColumnType("uuid");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasColumnName("key")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnName("name")
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("pk_company_roles");

                b.HasIndex("AppId", "Key")
                    .IsUnique()
                    .HasName("ix_company_roles_app_id_key");

                b.ToTable("company_roles");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyRoleClaim", b =>
            {
                b.Property<Guid>("RoleId")
                    .HasColumnName("role_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("ClaimId")
                    .HasColumnName("claim_id")
                    .HasColumnType("uuid");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnName("value")
                    .HasColumnType("text");

                b.HasKey("RoleId", "ClaimId")
                    .HasName("pk_company_role_claims");

                b.HasIndex("ClaimId")
                    .HasName("ix_company_role_claims_claim_id");

                b.ToTable("company_role_claims");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyUser", b =>
            {
                b.Property<Guid>("CompanyId")
                    .HasColumnName("company_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnName("user_id")
                    .HasColumnType("uuid");

                b.HasKey("CompanyId", "UserId")
                    .HasName("pk_company_users");

                b.HasIndex("UserId")
                    .HasName("ix_company_users_user_id");

                b.ToTable("company_users");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyUserClaim", b =>
            {
                b.Property<Guid>("CompanyId")
                    .HasColumnName("company_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnName("user_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("ClaimId")
                    .HasColumnName("claim_id")
                    .HasColumnType("uuid");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnName("value")
                    .HasColumnType("text");

                b.HasKey("CompanyId", "UserId", "ClaimId")
                    .HasName("pk_company_user_claims");

                b.HasIndex("ClaimId")
                    .HasName("ix_company_user_claims_claim_id");

                b.HasIndex("UserId")
                    .HasName("ix_company_user_claims_user_id");

                b.ToTable("company_user_claims");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyUserRole", b =>
            {
                b.Property<Guid>("CompanyId")
                    .HasColumnName("company_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnName("user_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("RoleId")
                    .HasColumnName("role_id")
                    .HasColumnType("uuid");

                b.HasKey("CompanyId", "UserId", "RoleId")
                    .HasName("pk_company_user_roles");

                b.HasIndex("RoleId")
                    .HasName("ix_company_user_roles_role_id");

                b.HasIndex("UserId")
                    .HasName("ix_company_user_roles_user_id");

                b.ToTable("company_user_roles");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.Role", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<Guid>("AppId")
                    .HasColumnName("app_id")
                    .HasColumnType("uuid");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasColumnName("key")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnName("name")
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("pk_roles");

                b.HasIndex("AppId", "Key")
                    .IsUnique()
                    .HasName("ix_roles_app_id_key");

                b.ToTable("roles");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.RoleClaim", b =>
            {
                b.Property<Guid>("RoleId")
                    .HasColumnName("role_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("ClaimId")
                    .HasColumnName("claim_id")
                    .HasColumnType("uuid");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnName("value")
                    .HasColumnType("text");

                b.HasKey("RoleId", "ClaimId")
                    .HasName("pk_role_claims");

                b.HasIndex("ClaimId")
                    .HasName("ix_role_claims_claim_id");

                b.ToTable("role_claims");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnName("email")
                    .HasColumnType("text");

                b.Property<string>("Login")
                    .IsRequired()
                    .HasColumnName("login")
                    .HasColumnType("text");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnName("password_hash")
                    .HasColumnType("text");

                b.Property<Guid?>("ReferralId")
                    .HasColumnName("referral_id")
                    .HasColumnType("uuid");

                b.HasKey("Id")
                    .HasName("pk_users");

                b.HasIndex("Email")
                    .IsUnique()
                    .HasName("ix_users_email");

                b.HasIndex("Login")
                    .IsUnique()
                    .HasName("ix_users_login");

                b.HasIndex("ReferralId")
                    .HasName("ix_users_referral_id");

                b.ToTable("users");

                b.HasData(
                    new
                    {
                        Id = new Guid("baa0ad0f-91c5-4c19-963c-ea369048e67a"),
                        Email = "a.kreskiyan@gmail.com",
                        Login = "alex",
                        PasswordHash = "ohraPG8QMZiOnXX+MWh/45aZDwjtv/7FQMFzXxSRxQjLdSMBHpELKDSznF6cSUalufovlgCfFkn4mtR7eXB+8w=="
                    });
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.UserClaim", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnName("user_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("ClaimId")
                    .HasColumnName("claim_id")
                    .HasColumnType("uuid");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnName("value")
                    .HasColumnType("text");

                b.HasKey("UserId", "ClaimId")
                    .HasName("pk_user_claims");

                b.HasIndex("ClaimId")
                    .HasName("ix_user_claims_claim_id");

                b.ToTable("user_claims");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.UserLogin", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<Guid>("AppId")
                    .HasColumnName("app_id")
                    .HasColumnType("uuid");

                b.Property<string>("Client")
                    .IsRequired()
                    .HasColumnName("client")
                    .HasColumnType("text");

                b.Property<string>("IPAddress")
                    .IsRequired()
                    .HasColumnName("ip_address")
                    .HasColumnType("text");

                b.Property<DateTime>("LoggedAt")
                    .HasColumnName("logged_at")
                    .HasColumnType("timestamp without time zone");

                b.Property<Guid>("RefreshToken")
                    .HasColumnName("refresh_token")
                    .HasColumnType("uuid");

                b.Property<DateTime>("RefreshTokenExpires")
                    .HasColumnName("refresh_token_expires")
                    .HasColumnType("timestamp without time zone");

                b.Property<Guid>("UserId")
                    .HasColumnName("user_id")
                    .HasColumnType("uuid");

                b.HasKey("Id")
                    .HasName("pk_user_logins");

                b.HasIndex("AppId")
                    .HasName("ix_user_logins_app_id");

                b.HasIndex("RefreshToken")
                    .IsUnique()
                    .HasName("ix_user_logins_refresh_token");

                b.HasIndex("UserId")
                    .HasName("ix_user_logins_user_id");

                b.ToTable("user_logins");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.UserRole", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnName("user_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("RoleId")
                    .HasColumnName("role_id")
                    .HasColumnType("uuid");

                b.HasKey("UserId", "RoleId")
                    .HasName("pk_user_roles");

                b.HasIndex("RoleId")
                    .HasName("ix_user_roles_role_id");

                b.ToTable("user_roles");
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.App", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.User", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .HasConstraintName("fk_apps_users_owner_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.Claim", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.App", null)
                    .WithMany()
                    .HasForeignKey("AppId")
                    .HasConstraintName("fk_claims_apps_app_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.Company", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .HasConstraintName("fk_companies_users_owner_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Annium.Id.Infrastructure.Db.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("ParentId")
                    .HasConstraintName("fk_companies_companies_parent_id")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyClaim", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.App", null)
                    .WithMany()
                    .HasForeignKey("AppId")
                    .HasConstraintName("fk_company_claims_apps_app_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyRole", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.App", null)
                    .WithMany()
                    .HasForeignKey("AppId")
                    .HasConstraintName("fk_company_roles_apps_app_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyRoleClaim", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.CompanyClaim", "Claim")
                    .WithMany()
                    .HasForeignKey("ClaimId")
                    .HasConstraintName("fk_company_role_claims_company_claims_claim_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Annium.Id.Infrastructure.Db.Entities.CompanyRole", "Role")
                    .WithMany("Claims")
                    .HasForeignKey("RoleId")
                    .HasConstraintName("fk_company_role_claims_company_roles_role_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyUser", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .HasConstraintName("fk_company_users_companies_company_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Annium.Id.Infrastructure.Db.Entities.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .HasConstraintName("fk_company_users_users_user_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyUserClaim", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.CompanyClaim", "Claim")
                    .WithMany()
                    .HasForeignKey("ClaimId")
                    .HasConstraintName("fk_company_user_claims_company_claims_claim_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Annium.Id.Infrastructure.Db.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .HasConstraintName("fk_company_user_claims_companies_company_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Annium.Id.Infrastructure.Db.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .HasConstraintName("fk_company_user_claims_users_user_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.CompanyUserRole", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .HasConstraintName("fk_company_user_roles_companies_company_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Annium.Id.Infrastructure.Db.Entities.CompanyRole", "Role")
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .HasConstraintName("fk_company_user_roles_company_roles_role_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Annium.Id.Infrastructure.Db.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .HasConstraintName("fk_company_user_roles_users_user_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.Role", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.App", null)
                    .WithMany()
                    .HasForeignKey("AppId")
                    .HasConstraintName("fk_roles_apps_app_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.RoleClaim", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.Claim", "Claim")
                    .WithMany()
                    .HasForeignKey("ClaimId")
                    .HasConstraintName("fk_role_claims_claims_claim_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Annium.Id.Infrastructure.Db.Entities.Role", "Role")
                    .WithMany("Claims")
                    .HasForeignKey("RoleId")
                    .HasConstraintName("fk_role_claims_roles_role_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.User", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("ReferralId")
                    .HasConstraintName("fk_users_users_referral_id")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.UserClaim", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.Claim", "Claim")
                    .WithMany()
                    .HasForeignKey("ClaimId")
                    .HasConstraintName("fk_user_claims_claims_claim_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Annium.Id.Infrastructure.Db.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .HasConstraintName("fk_user_claims_users_user_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.UserLogin", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.App", null)
                    .WithMany()
                    .HasForeignKey("AppId")
                    .HasConstraintName("fk_user_logins_apps_app_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Annium.Id.Infrastructure.Db.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .HasConstraintName("fk_user_logins_users_user_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Annium.Id.Infrastructure.Db.Entities.UserRole", b =>
            {
                b.HasOne("Annium.Id.Infrastructure.Db.Entities.Role", "Role")
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .HasConstraintName("fk_user_roles_roles_role_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Annium.Id.Infrastructure.Db.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .HasConstraintName("fk_user_roles_users_user_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}