<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Id</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../lib/src/Annium.Id.Core/Annium.Id.Core.csproj" />
    <ProjectReference Include="../Server.Domain/Server.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Configuration.Yaml" />
    <PackageReference Include="Annium.DbUp.PostgreSql" />
    <PackageReference Include="Annium.linq2db.PostgreSql" />
    <PackageReference Include="Annium.Logging.Console" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Scripts/**/*.sql" />
  </ItemGroup>
</Project>
