version: '3.7'
services:
  api:
    build:
      context: ../server
      dockerfile: src/Annium.Id.Api/Dockerfile
    image: id_api
    container_name: id_api
    restart: always
    ports:
      - '9501:5000'
    volumes:
      - '../run/configuration:/app/configuration'
      - '../run/keys:/app/keys'
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '1'
networks:
  default:
    external:
      name: id_net
