version: '3.7'
services:
  api:
    build:
      context: ../server/web/src/site
      dockerfile: Dockerfile
    image: id_site
    container_name: id_site
    restart: always
    ports:
      - '9500:80'
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '1'
networks:
  default:
    external:
      name: id_net
