<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Id</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Server.Db/Server.Db.csproj" />
    <ProjectReference Include="../Server.Email/Server.Email.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Architecture.Mediator" />
    <PackageReference Include="Annium.Localization.Yaml" />
  </ItemGroup>
  <ItemGroup>
    <None Update="**/locale/*.yml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
