<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Id</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Server.Domain/Server.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Configuration.Yaml" />
    <PackageReference Include="Annium.Net.Mail" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Templates/*.html" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
